fazh/config/routes.rb
Rails.application.routes.draw do
  resources :attendances
  get 'dashboard/index'
  root 'home#index'

   resources :users
   resources :sessions, only: [:new, :create, :destroy]
   
   get 'signup', to: 'users#new', as: 'signup'
   get 'login', to: 'sessions#new', as: 'login'
   get 'logout', to: 'sessions#destroy', as: 'logout'
end

fazh/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

fazh/app/models/attendance.rb
class Attendance < ApplicationRecord
end

fazh/app/models/home.rb
class Home < ApplicationRecord
end

fazh/app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
end

fazh/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
   if session[:user_id]
     @current_user ||= User.find(session[:user_id])
   else
     @current_user = nil
   end
 end
end

fazh/app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :set_attendance, only: [:show, :edit, :update, :destroy]

  # GET /attendances
  # GET /attendances.json
  def index
    @attendances = Attendance.all
  end

  # GET /attendances/1
  # GET /attendances/1.json
  def show
  end

  # GET /attendances/new
  def new
    @attendance = Attendance.new
  end

  # GET /attendances/1/edit
  def edit
  end

  # POST /attendances
  # POST /attendances.json
  def create
    @attendance = Attendance.new(attendance_params)

    respond_to do |format|
      if @attendance.save
        format.html { redirect_to @attendance, notice: 'Attendance was successfully created.' }
        format.json { render :show, status: :created, location: @attendance }
      else
        format.html { render :new }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendances/1
  # PATCH/PUT /attendances/1.json
  def update
    respond_to do |format|
      if @attendance.update(attendance_params)
        format.html { redirect_to @attendance, notice: 'Attendance was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance }
      else
        format.html { render :edit }
        format.json { render json: @attendance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendances/1
  # DELETE /attendances/1.json
  def destroy
    @attendance.destroy
    respond_to do |format|
      format.html { redirect_to attendances_url, notice: 'Attendance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance
      @attendance = Attendance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_params
      params.require(:attendance).permit(:student, :gender, :admissionid, :admissiondate, :studentclass, :days, :mark, :result, :perfomance, :test, :fees)
    end
end

fazh/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @attendances = Attendance.all
  end
end

fazh/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @home = Home.all
  end
end

fazh/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

fazh/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :school_name, :email, :password, :password_confirmation)
    end
end

fazh/app/helpers/application_helper.rb
module ApplicationHelper
end

fazh/app/helpers/attendances_helper.rb
module AttendancesHelper
end

fazh/app/helpers/dashboard_helper.rb
module DashboardHelper
end

fazh/app/helpers/home_helper.rb
module HomeHelper
end

fazh/app/helpers/sessions_helper.rb
module SessionsHelper
end

fazh/app/helpers/users_helper.rb
module UsersHelper
end

fazh/app/views/attendances/_form.html.erb
<%= form_with(model: attendance, local: true) do |form| %>
  <% if attendance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance.errors.count, "error") %> prohibited this attendance from being saved:</h2>

      <ul>
      <% attendance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student %>
    <%= form.text_field :student %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.text_field :gender %>
  </div>

  <div class="field">
    <%= form.label :admissionid %>
    <%= form.number_field :admissionid %>
  </div>

  <div class="field">
    <%= form.label :admissiondate %>
    <%= form.date_select :admissiondate %>
  </div>

  <div class="field">
    <%= form.label :studentclass %>
    <%= form.text_field :studentclass %>
  </div>

  <div class="field">
    <%= form.label :days %>
    <%= form.number_field :days %>
  </div>

  <div class="field">
    <%= form.label :mark %>
    <%= form.number_field :mark %>
  </div>

  <div class="field">
    <%= form.label :result %>
    <%= form.text_field :result %>
  </div>

  <div class="field">
    <%= form.label :perfomance %>
    <%= form.text_area :perfomance %>
  </div>

  <div class="field">
    <%= form.label :test %>
    <%= form.number_field :test %>
  </div>

  <div class="field">
    <%= form.label :fees %>
    <%= form.text_field :fees %>
  </div>
  <div class="field">
    <%= form.label :english %>
    <%= form.text_field :english %>
  </div>

  <div class="field">
    <%= form.label :mathematics %>
    <%= form.text_field :mathematics %>
  </div>

  <div class="field">
    <%= form.label :geography %>
    <%= form.text_field :geography %>
  </div>

  <div class="field">
    <%= form.label :history %>
    <%= form.text_field :history %>
  </div>

  <div class="field">
    <%= form.label :agriculture %>
    <%= form.text_field :agriculture %>
  </div>

  <div class="field">
    <%= form.label :commerce %>
    <%= form.text_field :commerce %>
  </div>

  <div class="field">
    <%= form.label :accounting %>
    <%= form.text_field :accounting %>
  </div>

  <div class="field">
    <%= form.label :literature %>
    <%= form.text_field :literature %>
  </div>

  <div class="field">
    <%= form.label :shona %>
    <%= form.text_area :shona %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

fazh/app/views/attendances/edit.html.erb
<h1>Editing Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Show', @attendance %> |
<%= link_to 'Back', attendances_path %>

fazh/app/views/attendances/index.html.erb
<p id="notice"><%= notice %></p>
<div class="grid-container">
  <div class="menu-icon">
   <i class="fas fa-bars header__menu"></i>
 </div>

 <header class="header">
   <div class="header__search">Search...</div>
   <div class="header__avatar">Your face</div>
 </header>

 <aside class="sidenav">
   <div class="sidenav__close-icon">
     <i class="fas fa-times sidenav__brand-close"></i>
   </div>
   <ul class="sidenav__list">
     <li class="sidenav__list-item">Teachers</li>
     <li class="sidenav__list-item">Library</li>
     <li class="sidenav__list-item">Assessment</li>
     <li class="sidenav__list-item">Notice</li>
     <li class="sidenav__list-item">Subject</li>
     <li class="sidenav__list-item">Parents</li>
     <li class="sidenav__list-item">Students</li>
     <li class="sidenav__list-item">Assignments</li>
     <li class="sidenav__list-item">Events</li>
     <li class="sidenav__list-item">Exams</li>
   </ul>
 </aside>

 <main class="main">
   <div class="main-header">
     <div class="main-header__heading">Hello User</div>
     <div class="main-header__updates">Recent Items</div>
   </div>

   <div class="main-cards">
     <table>
       <thead>
         <tr>
           <th>Student</th>
           <th>Gender</th>
           <th>ID</th>
           <th>Admission Date</th>
           <th>Class</th>
           <th>Days</th>
           <th colspan="3">Manage data</th>
         </tr>
       </thead>

       <tbody>
         <% @attendances.each do |attendance| %>
           <tr>
             <td><%= attendance.student %></td>
             <td><%= attendance.gender %></td>
             <td>#<%= attendance.admissionid %></td>
             <td><%= attendance.admissiondate %></td>
             <td><%= attendance.studentclass %></td>
             <td><%= attendance.days %></td>
             <td><%= link_to 'Show', attendance %></td>
             <td><%= link_to 'Edit', edit_attendance_path(attendance) %></td>
             <td><%= link_to 'Destroy', attendance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           </tr>
         <% end %>
       </tbody>
     </table>

     <br>

     <%= link_to 'New Student', new_attendance_path %>

   </div>
 </main>

 <footer class="footer">
   <div class="footer__copyright">&copy; 2018 MTH</div>
   <div class="footer__signature">Made with love by pure genius</div>
 </footer>
</div>

fazh/app/views/attendances/new.html.erb
<h1>New Attendance</h1>

<%= render 'form', attendance: @attendance %>

<%= link_to 'Back', attendances_path %>

fazh/app/views/attendances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @attendance.student %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @attendance.gender %>
</p>

<p>
  <strong>Admissionid:</strong>
  <%= @attendance.admissionid %>
</p>

<p>
  <strong>Admissiondate:</strong>
  <%= @attendance.admissiondate %>
</p>

<p>
  <strong>Studentclass:</strong>
  <%= @attendance.studentclass %>
</p>

<p>
  <strong>Days:</strong>
  <%= @attendance.days %>
</p>

<p>
  <strong>Mark:</strong>
  <%= @attendance.mark %>
</p>

<p>
  <strong>Result:</strong>
  <%= @attendance.result %>
</p>

<p>
  <strong>Perfomance:</strong>
  <%= @attendance.perfomance %>
</p>

<p>
  <strong>Test:</strong>
  <%= @attendance.test %>
</p>

<p>
  <strong>Fees:</strong>
  <%= @attendance.fees %>
</p>
<p>

<p>
  <strong>English:</strong>
  <%= @attendance.english %>
</p>

<p>
  <strong>Mathematics:</strong>
  <%= @attendance.mathematics %>
</p>

<p>
  <strong>Geography:</strong>
  <%= @attendance.geography %>
</p>

<p>
  <strong>History:</strong>
  <%= @attendance.history %>
</p>

<p>
  <strong>Agriculture:</strong>
  <%= @attendance.agriculture %>
</p>

<p>
  <strong>Commerce:</strong>
  <%= @attendance.commerce %>
</p>

<p>
  <strong>Accounting:</strong>
  <%= @attendance.accounting %>
</p>

<p>
  <strong>Literature:</strong>
  <%= @attendance.literature %>
</p>

<p>
  <strong>Shona:</strong>
  <%= @attendance.shona %>
</p>

<%= link_to 'Edit', edit_attendance_path(@attendance) %> |
<%= link_to 'Back', attendances_path %>

fazh/app/views/dashboard/index.html.erb
<div class="grid-container">
  <div class="menu-icon">
   <i class="fas fa-bars header__menu"></i>
 </div>

 <header class="header">
   <div class="header__search">Search...</div>
   <div class="header__avatar">Your face</div>
 </header>

 <aside class="sidenav">
   <div class="sidenav__close-icon">
     <i class="fas fa-times sidenav__brand-close"></i>
   </div>
   <ul class="sidenav__list">
     <li class="sidenav__list-item">Teachers</li>
     <li class="sidenav__list-item">Library</li>
     <li class="sidenav__list-item">Assessment</li>
     <li class="sidenav__list-item">Notice</li>
     <li class="sidenav__list-item">Subject</li>
     <li class="sidenav__list-item">Parents</li>
     <li class="sidenav__list-item">Students</li>
     <li class="sidenav__list-item">Assignments</li>
     <li class="sidenav__list-item">Events</li>
     <li class="sidenav__list-item">Exams</li>
   </ul>
 </aside>

 <main class="main">
   <div class="main-header">
     <div class="main-header__heading">Hello User</div>
     <div class="main-header__updates">Recent Items</div>
   </div>

   <div class="main-overview">
     <div class="overviewcard">
       <div class="overviewcard__icon">Overview</div>
       <div class="overviewcard__info">Fees</div>
     </div>
     <div class="overviewcard">
       <div class="overviewcard__icon">Overview</div>
       <div class="overviewcard__info">Card</div>
     </div>
     <div class="overviewcard">
       <div class="overviewcard__icon">Overview</div>
       <div class="overviewcard__info">Card</div>
     </div>
     <div class="overviewcard">
       <div class="overviewcard__icon">Overview</div>
       <div class="overviewcard__info">Card</div>
     </div>
   </div>

   <div class="main-cards">
     <div class="card">Perfomance</div>
     <div class="card">Test Records</div>
     <div class="card">
       <ul>
         <% @attendances.each do |attendance| %>
          <li><%= attendance.student %></li>
         <% end %>
       </ul>
     </div>
   </div>
 </main>

 <footer class="footer">
   <div class="footer__copyright">&copy; 2018 MTH</div>
   <div class="footer__signature">Made with love by pure genius</div>
 </footer>
</div>

fazh/app/views/home/index.html.erb
<div class="head">
  <h1>LOGO</h1>
  <div class="account">
    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to 'Log Out', logout_path %>
      <% else %>
      <%= link_to 'Sign Up', signup_path %> or
      <%= link_to 'Log In', login_path %>
    <% end %>
  </div>
</div>
<div class="school-updates">
  <% @home.each do |home| %>
    <h4><%= home.title %></h4>
    <p><%= home.body %></p>
  <% end %>
</div>

fazh/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fazh</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

fazh/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :school_name %>
    <%= form.text_field :school_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

fazh/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

fazh/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>School name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.school_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

fazh/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

fazh/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>School name:</strong>
  <%= @user.school_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>